### ISSUE TITLE
Multiverse and GemsEconomy conflict [BUG]

### ISSUE THREAD

**Issue by JuanDavidSolano** [bennycio/TownyMenu#1]
**Describe the bug**
The plugin disable Multiverse and dont work with GemsEconomy, so when i try to use /townmenu it crashes

**To Reproduce**
1. Install Multiverse and gemseconomy
2. Enable Vault hook on gemseconomy
3. Execute /townmenu

**Expected behavior**
See the town menu

**Screenshots**
https://gist.github.com/JuanDavidSolano/6f4154a1bb883c2d81affedfc4cf3400

**Plugin Version:**
1.0.5

**Server Jar and Version:**
Paper-179

**Additional context**

**Comment by benny-conn** [comment]
Gems Economy conflicts with Towny and therefore conflicts with TownyMenu. Unfortunately another economy plugin must be used to not conflict.
