### ISSUE TITLE
Towny Menu and Multiverse

### ISSUE THREAD

**Issue by cobrex1** [bennycio/TownyMenu#2]
**Describe the bug**
TownyMenu breaks Multiversecore 4.0

**To Reproduce**
1.
Using paper 1.16.1 # 133
Load in:
Towny 0.96.2.16
Multiversecore 4.1.0
TownyMenue 1.0.6

2. On load, Multiverse disables

4. https://hastebin.com/ixadilazen.md

**Expected behavior**
Multiverse core enables.

Disabled TownyMenu 1.0.6 and all plugins on the server load fine

**Comment by benny-conn** [comment]
https://www.spigotmc.org/resources/towny-menu.83443/update?update=359527

Hope this solves your issue!
