### ISSUE TITLE
Conflict with titelmanger and error with /townymenu

### ISSUE THREAD

**Issue by cobrex1** [bennycio/TownyMenu#3]
**Describe the bug**
Unable to use the /townmenu command either as /op or a town mayor.
permission was added to the townyperm.yml for mayor and assistant.

I am also unable to use the /tm command as this conflicts with titlemanager plugin.

**To Reproduce**

Paper 1.16.1 # 133
Townymenu 1.0.8
Towny 0.96.2.16
Any titelmanager version (2.3.1 I have)

**Expected behavior**
Access the townmenu menu - error on access.

error.log below:

https://hastebin.com/etuhohisiz.rb

https://hastebin.com/avodabebut.sql

**Comment by benny-conn** [comment]
https://github.com/Tolmikarc/TownyMenu#townymenu

For Pre-Release support, download here!
