### ISSUE TITLE
[BUG] Command error

### ISSUE THREAD

**Issue by myavuzokumus** [bennycio/TownyMenu#4]
**Describe the bug**
When type /townmenu, appear this error:
[error.log](https://github.com/Tolmikarc/TownyMenu/files/5249385/error.log)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/47111280/93663175-653c0400-fa6e-11ea-80c5-efe2ab3fdbc4.png)

**Plugin Version:**
![image](https://user-images.githubusercontent.com/47111280/93663193-90265800-fa6e-11ea-850c-a8f18dee2c44.png)
![image](https://user-images.githubusercontent.com/47111280/93663219-c06df680-fa6e-11ea-8194-b35c0ffecdec.png)

**Server Jar and Version:**
![image](https://user-images.githubusercontent.com/47111280/93663187-8a307700-fa6e-11ea-832c-20f44c7b5470.png)

**Additional context**

**Comment by benny-conn** [comment]
Because you are using a pre-release of towny, please use a pre-release version of Towny Menu. You can find this at https://github.com/Tolmikarc/TownyMenu/releases/tag/v1.1.7-PRE
