### ISSUE TITLE
[BUG] Error on interact

### ISSUE THREAD

**Issue by Kbryst** [bennycio/TownyMenu#6]
Error gets printed when player runs command, menu does not open. Player is a mayor.

https://pastebin.com/YEbnnVqQ

Towny Menu 1.2.0
Using CMI for economy, Towny 0.96.2.19
Paper 1.16.3 - 214

**Comment by benny-conn** [comment]
Please use the pre-release version of the plugin because you are using the pre-release version of towny. https://github.com/Tolmikarc/TownyMenu/releases/tag/v.1.2.0-PRE

**Comment by Kbryst** [comment]
I'm..... not?

**Comment by benny-conn** [comment]
Towny 0.96.2.19 is a pre-release. https://i.imgur.com/fTZd31p.png
