### ISSUE TITLE
[FEATURE] Command /townymenu reload

### ISSUE THREAD

**Issue by aldoapicella** [bennycio/TownyMenu#7]
**Is your feature request related to a problem? Please describe.**
Plugin stop working when reloaded with Plugman or another plugin manager, it is a little bit frustrating having to restart the hole server to make language changes.

**Describe the solution you'd like**
Add command /townymenu reload to reload the plugin.

**Comment by benny-conn** [comment]
Great suggestion, I will be working on a reload feature in the near future!
